services:
  - type: web
    name: stbchef-web
    runtime: python
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install poetry
      poetry install --no-interaction --no-root

      # Install JavaScript dependencies and build static assets
      npm install --legacy-peer-deps
      npm run build
    startCommand: poetry run python -m src.web.app

    envVars:
      # --- Secrets / configuration ---
      # Wallet & blockchain configuration
      - key: PRIVATE_KEY           # EOA private key for contract deployments / tx signing
        sync: false
      - key: LINEA_RPC_URL
        sync: false
      - key: LINEA_TESTNET_RPC_URL
        sync: false
      - key: CHAIN_ID
        sync: false
      - key: TESTNET_CHAIN_ID
        sync: false

      # Block-explorer API keys
      - key: LINEASCAN_API_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false

      # Optional AI model API keys
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false 