name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- Python setup -----------------
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Python dependencies
        run: |
          poetry install --no-interaction --no-root

      # ---------------- Node setup -------------------
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm install --legacy-peer-deps

      # --------------- Lint & Tests ------------------
      - name: Run ESLint
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then npm run lint --if-present; fi

      - name: Run JavaScript tests
        run: |
          npm test --if-present

      - name: Compile & test Hardhat contracts
        run: |
          npx hardhat compile && npx hardhat test

      - name: Run Python tests
        run: |
          poetry run pytest -q 